#!/bin/sh

JEMALLOC_URL=https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2
PREFIX=/usr/local

# build and install jemalloc
curl -LO $JEMALLOC_URL
tar xjf jemalloc-*.tar.bz2 --no-same-owner
rm jemalloc-*.tar.bz2
cd jemalloc-*.*.*
./configure --prefix=$PREFIX \
    --disable-shared \
    --enable-static \
    --disable-stats \
    --disable-initial-exec-tls \
    --disable-doc \
    --with-jemalloc-prefix=numbirch_ \
    --with-install-suffix=_numbirch
make
make install
cd ..
rm -rf jemalloc-*.*.*

# symlink math_functions.h to math_functions.hpp, expected by some older
# versions of Eigen
ln -sf /usr/local/cuda/include/math_functions.h /usr/local/cuda/include/math_functions.hpp

# install wrapper
install nvcc_wrapper $PREFIX/bin
