site_name: Indii.org Software Repository
site_description: Software repository for Doxide and Birch, with packages for major Linux distributions as well as Homebrew packages for macOS.
theme:
  name: material
  icon:
    logo: material/download
  features:
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue-grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    admonition:
      warning: simple/ubuntu
      bug: simple/debian
      abstract: simple/fedora
      question: simple/opensuse

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins: []  # disable search

