site_name: download.indii.org
site_description: Linux package repository for Mending Wall, Doxide and Birch.
site_url: https://download.indii.org
extra:
  social:
    - icon: heart
      link: https://github.com/sponsors/lawmurray
      name: Sponsor
    - icon: material/github
      link: https://github.com/lawmurray
      name: GitHub
    - icon: material/mastodon 
      link: https://fosstodon.org/@lawmurray
      name: Mastodon
    - icon: material/web
      link: https://indii.org
      name: Website (indii.org)
    - icon: material/email
      link: mailto:lawrence@indii.org
      name: Email
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: material/github
    admonition:
      success: material/package-down

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins: []  # disable search

